### PR TITLE
fix the contributing

### PR DESCRIPTION
**Pull request by dd-jy**
## Description
(Please describe what this PR do.)
fix the contributing

## Type of change
Please insert 'x' one of the type of change.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [x] Refactoring, Maintenance
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by soimkim** [comment]
Dear @dd-jy ,
Is this PR for testing?
The only changes to the file are adding "."

**Comment by dd-jy** [comment]
Actually, I cannot remember it...
But it seems to be not bad to be merged.

**Comment by soimkim** [comment]
@dd-jy , Merge anytime you want. :-)

**Comment by soimkim** [comment]
@hyesung2 메일 어떤걸로 가시나요? (test)

**Pull request merged**
